FROM python:3.8.18-slim

# Supervisord.conf
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# ENV CUDA
ENV PATH=/usr/local/cuda-11/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-11/lib64:$LD_LIBRARY_PATH

# Install system packages
RUN apt-get update \
    && apt-get install -y \
    apt-utils \
    supervisor \
    curl \
    python3-pip \
    dumb-init \
    build-essential \
    libgomp1 \
    tesseract-ocr \
    libtesseract-dev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    libglib2.0-0 \
    wget \
    && apt-get autoremove -y \
    && apt-get autoclean -y \
    && rm -rf /var/lib/apt/lists/*

# Install py env
COPY requirements.txt api_requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r api_requirements.txt

# Install CUDA 11.2.2
RUN wget -qO /etc/apt/preferences.d/cuda-repository-pin-600 \
    https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin \
    && wget -qO cuda-repo.deb \
    https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda-repo-wsl-ubuntu-11-2-local_11.2.2-1_amd64.deb \
    && dpkg -i cuda-repo.deb \
    && apt-key add /var/cuda-repo-wsl-ubuntu-11-2-local/7fa2af80.pub \
    && apt-get update \
    && apt-get install -y --no-install-recommends cuda \
    && rm -rf /var/cuda-repo-wsl-ubuntu-11-2-local cuda-repo.deb

# Install cuDNN 8.1.1
RUN wget -qO cudnn.tgz \
    https://developer.download.nvidia.com/compute/redist/cudnn/v8.1.1/cudnn-11.2-linux-x64-v8.1.1.33.tgz \
    && tar -xzvf cudnn.tgz -C /usr/local --strip-components=1 \
    && rm cudnn.tgz

# Install TensorRT 7.2.3.4
RUN pip3 install --upgrade setuptools pip \
    && pip3 install nvidia-pyindex \
    && pip3 install nvidia-tensorrt==7.2.3.4 \ 
    && cp -R /usr/local/lib/python3.8/site-packages/tensorrt/* /usr/local/cuda-11.2/lib64 \
    && cp -R /usr/local/lib/python3.8/site-packages/nvidia/cuda_nvrtc/lib/* /usr/local/cuda-11.2/lib64 \
    && cp -R /usr/local/lib/python3.8/site-packages/nvidia/cudnn/lib/* /usr/local/cuda-11.2/lib64

# Minimize image size
RUN apt-get autoremove -y; apt-get autoclean -y

# Start api with end-point supervisord
CMD ["/usr/bin/supervisord"]