FROM apache/airflow:slim-2.5.1-python3.8

ENV AIRFLOW_UID=50000
ENV AIRFLOW_GID=0
ENV PATH=/usr/local/cuda-11/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-11/lib64:$LD_LIBRARY_PATH

# Install system packages
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        dumb-init \
        build-essential \
        libxgboost-dev \
        default-libmysqlclient-dev \
        libmariadb-dev \
        libgl1-mesa-glx \
        libglib2.0-0 \
        wget \
    && apt-get autoremove -y \
    && apt-get autoclean -y \
    && rm -rf /var/lib/apt/lists/*

# Change owner and create airflow user
RUN chown airflow /bin/bash

# Add user airflow to root group and grant sudo privileges
RUN usermod -aG root airflow \
    && echo "airflow ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Change work directory
WORKDIR /opt/airflow
RUN chmod -R 755 /opt/airflow/logs
RUN chown -R airflow /opt/airflow/logs


# Install CUDA 11.2.2
RUN wget -qO /etc/apt/preferences.d/cuda-repository-pin-600 \
    https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin \
    && wget -qO cuda-repo.deb \
    https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda-repo-wsl-ubuntu-11-2-local_11.2.2-1_amd64.deb \
    && dpkg -i cuda-repo.deb \
    && apt-key add /var/cuda-repo-wsl-ubuntu-11-2-local/7fa2af80.pub \
    && apt-get update \
    && apt-get install -y --no-install-recommends cuda \
    && rm -rf /var/cuda-repo-wsl-ubuntu-11-2-local cuda-repo.deb

# Install cuDNN 8.1.1
RUN wget -qO cudnn.tgz \
    https://developer.download.nvidia.com/compute/redist/cudnn/v8.1.1/cudnn-11.2-linux-x64-v8.1.1.33.tgz \
    && tar -xzvf cudnn.tgz -C /usr/local --strip-components=1 \
    && rm cudnn.tgz

# Install Python dependencies
USER airflow
COPY requirements.txt airflow_requirements.txt
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir -r airflow_requirements.txt \
    && rm airflow_requirements.txt

# Install TensorRT 7.2.3
RUN pip3 install --upgrade setuptools pip \
    && pip3 install nvidia-pyindex \
    && pip3 install nvidia-tensorrt==7.2.3.4 \
    && sudo cp -R $HOME/.local/lib/python3.8/site-packages/tensorrt/* /usr/local/cuda-11/lib64 \
    && sudo cp -R $HOME/.local/lib/python3.8/site-packages/nvidia/cuda_nvrtc/lib/* /usr/local/cuda-11/lib64 \
    && sudo cp -R $HOME/.local/lib/python3.8/site-packages/nvidia/cudnn/lib/* /usr/local/cuda-11/lib64

# # Clean up TensorRT package
# RUN pip3 uninstall nvidia-tensorrt --yes

# Minimize image size
USER root
RUN apt-get autoremove -y \
    && apt-get autoclean -y \
    && rm -rf /var/lib/apt/lists/*

# With wanning (The NUMA information is a non-harmful warning. Tensorflow can run correctly with the warning.)
# https://forums.developer.nvidia.com/t/numa-error-running-tensorflow-on-jetson-tx2/56119/2
